export const PASSWORDLESS_LOGIN_CODE_LENGTH = 6
export const PASSWORDLESS_LOGIN_CONTINUATION_TTL_SECONDS = 15 * 60
export const PASSWORDLESS_LOGIN_RESEND_COOLDOWN_SECONDS = 60
export const PASSWORDLESS_LOGIN_TTL_SECONDS = 15 * 60
